name: Python package

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7.5]
        # python-version: [3.5.7, 3.6.10, 3.7.5, 3.8.2]

    steps:
    - uses: actions/checkout@v2
    - uses: ./action-b
      with:
        python-version: ${{ matrix.python-version }}
        IS_TEST_NEEDED: true
